# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "setup"
  - "clone"
  - "build"
  - "test"

steps:
  destination:
    stage: setup
    title: Destination AWS Environment
    image: codefresh/cli:latest
    commands:
      - echo $CF_PRERELEASE_FLAG
      - echo $CF_RELEASE_TAG
      - echo $AWS_DESTINATION
      
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "bimal-desai/harsh-api"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "harsh-Github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "bimal-desai/harsh-api"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"

