# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "setup"
  - "clone"
  - "build"
  - "test"

steps:
  env_var_test:
    title: Create and export RFC 1035 names for repo and branch
    stage: setup
    image: alpine
    commands:
      # make RFC 1035 Label Names for repo and branch
      - export NORMALIZED_REPO=$(echo $CF_REPO_NAME | tr '[:upper:]' '[:lower:]' | sed 's/[^[:alnum:]\-]/-/g' | sed 's/^[^a-z]*//' | sed 's/[^[:alnum:]]*$//' | sed 's/^\(.\{0,64\}\).*$/\1/')
      - export NORMALIZED_BRANCH=$(echo $CF_BRANCH | awk -F/ '{ print $1 }' | tr '[:upper:]' '[:lower:]' | sed 's/[^[:alnum:]\-]/-/g' | sed 's/^[^a-z]*//' | sed 's/[^[:alnum:]]*$//' | sed 's/^\(.\{0,64\}\).*$/\1/')
      - cf_export NORMALIZED_REPO NORMALIZED_BRANCH
      
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "bimal-desai/harsh-api"
    revision: "${{CF_BRANCH}}"
    git: "harsh-Github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: ${{NORMALIZED_REPO}}
    working_directory: "${{clone}}"
    tag: "${{CF_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"

